// NEIFE Mock Data

export const specialties = [
  "Derecho Laboral",
  "Derecho de Familia",
  "Derecho Civil",
  "Derecho Penal",
  "Derecho Inmobiliario",
  "Derecho Comercial",
  "Propiedad Intelectual",
  "Derecho Tributario",
  "Deudas e Insolvencia",
  "Extranjería y Migración",
] as const

export const cities = [
  "Santiago",
  "Valparaíso",
  "Concepción",
  "Temuco",
  "La Serena",
  "Iquique",
  "Puerto Montt",
] as const

export const statusConfig = {
  active: { label: "Activo", bg: "bg-[#5E8B8C]", text: "text-white" },
  pending: { label: "Pendiente", bg: "bg-[#C27F79]", text: "text-white" },
  waiting: { label: "Esperando abogado", bg: "bg-[#F2C94C]", text: "text-[#2D3C3C]" },
  completed: { label: "Completado", bg: "bg-[#D5C3B6]", text: "text-[#2D3C3C]" },
  inProgress: { label: "En Progreso", bg: "bg-[#F2C94C]", text: "text-[#2D3C3C]" },
  rejected: { label: "Declinado", bg: "bg-[#D5C3B6]/50", text: "text-[#75524C]" },
}

// Solicitudes entrantes para abogados
export const mockIncomingRequests = [
  {
    id: "req1",
    clientName: "Javiera Fernandez",
    clientType: "Particular",
    caseTitle: "Divorcio consensual",
    caseType: "Derecho Familiar",
    description: "Necesito asesoria para tramitar un divorcio de mutuo acuerdo. Tenemos bienes compartidos y un hijo menor.",
    budget: 120,
    message: "Hola, vi su perfil y me parece que tiene mucha experiencia en casos de familia. Podria ayudarme?",
    submittedAt: "hace 2 horas",
    status: "pending" as const,
  },
  {
    id: "req2",
    clientName: "Carlos Mendez",
    clientType: "Empresa",
    caseTitle: "Revision de contrato comercial",
    caseType: "Derecho Comercial",
    description: "Tengo un contrato de distribucion que necesito revisar antes de firmar. Hay clausulas que me preocupan.",
    budget: 150,
    message: "Busco un abogado para una revision urgente antes del viernes.",
    submittedAt: "hace 5 horas",
    status: "pending" as const,
  },
]

export const mockLawyers = [
  {
    id: 1,
    name: "Dra. María González",
    specialty: "Derecho de Familia",
    city: "Santiago",
    rate: 120,
    rating: 4.9,
    reviews: 47,
    experience: 12,
    successRate: 94,
    verified: true,
    freeConsult: true,
    paymentPlan: true,
    contingency: false,
    available: true,
    bio: "Especialista en derecho de familia con más de 12 años de experiencia en divorcios, tuición y pensiones alimenticias. Egresada de la Universidad de Chile.",
    tags: ["Derecho de Familia", "Divorcios", "Civil"],
    reviewsList: [
      { author: "M.F.", text: "Excelente profesional, resolvio mi caso de divorcio con mucha empatia y eficiencia.", rating: 5, date: "Enero 2025" },
      { author: "C.R.", text: "Muy clara explicando los pasos a seguir. La recomiendo completamente.", rating: 5, date: "Diciembre 2024" },
      { author: "A.P.", text: "Buena comunicacion y resultados. El proceso fue mas rapido de lo esperado.", rating: 4, date: "Noviembre 2024" },
    ],
  },
  {
    id: 2,
    name: "Dr. Carlos Ruiz",
    specialty: "Derecho Laboral",
    city: "Valparaíso",
    rate: 85,
    rating: 4.7,
    reviews: 32,
    experience: 8,
    successRate: 88,
    verified: true,
    freeConsult: false,
    paymentPlan: true,
    contingency: true,
    available: true,
    bio: "Abogado laboralista enfocado en defender los derechos de los trabajadores. Especialista en despidos injustificados y negociación colectiva.",
    tags: ["Derecho Laboral", "Despidos", "Negociación"],
    reviewsList: [
      { author: "J.M.", text: "Me ayudo a ganar mi demanda por despido injustificado. Muy profesional.", rating: 5, date: "Febrero 2025" },
      { author: "P.S.", text: "Conoce muy bien la ley laboral. Consiguio una buena indemnizacion.", rating: 5, date: "Enero 2025" },
      { author: "R.L.", text: "Buen abogado, aunque las respuestas podrian ser mas rapidas.", rating: 4, date: "Diciembre 2024" },
    ],
  },
  {
    id: 3,
    name: "Dr. Andrés Muñoz",
    specialty: "Derecho Penal",
    city: "Santiago",
    rate: 200,
    rating: 4.8,
    reviews: 61,
    experience: 18,
    successRate: 91,
    verified: true,
    freeConsult: false,
    paymentPlan: false,
    contingency: false,
    available: false,
    bio: "Defensor penal con amplia trayectoria en casos de alta complejidad. Ex fiscal del Ministerio Público.",
    tags: ["Derecho Penal", "Defensa Criminal", "Delitos"],
    reviewsList: [
      { author: "F.G.", text: "Defensa impecable. Su experiencia como ex fiscal marco la diferencia.", rating: 5, date: "Marzo 2025" },
      { author: "M.T.", text: "Profesional serio y con mucho conocimiento. Excelente resultado.", rating: 5, date: "Febrero 2025" },
      { author: "S.V.", text: "Caro pero vale cada peso. Sabe lo que hace.", rating: 5, date: "Enero 2025" },
    ],
  },
  {
    id: 4,
    name: "Dra. Ana López",
    specialty: "Derecho Inmobiliario",
    city: "Concepción",
    rate: 95,
    rating: 4.6,
    reviews: 28,
    experience: 7,
    successRate: 85,
    verified: true,
    freeConsult: true,
    paymentPlan: true,
    contingency: false,
    available: true,
    bio: "Especialista en compraventa de propiedades, arriendos y regularización de títulos. Experiencia con proyectos inmobiliarios.",
    tags: ["Derecho Inmobiliario", "Compraventa", "Arriendos"],
    reviewsList: [
      { author: "L.M.", text: "Reviso todos los documentos de mi compra de departamento. Muy detallista.", rating: 5, date: "Enero 2025" },
      { author: "D.C.", text: "Buena asesora para temas de arriendos. Recomendada.", rating: 4, date: "Diciembre 2024" },
      { author: "H.R.", text: "Profesional y puntual. Regularizo mi titulo sin problemas.", rating: 5, date: "Noviembre 2024" },
    ],
  },
  {
    id: 5,
    name: "Dr. Pedro Vásquez",
    specialty: "Derecho Comercial",
    city: "Santiago",
    rate: 150,
    rating: 4.5,
    reviews: 19,
    experience: 10,
    successRate: 87,
    verified: false,
    freeConsult: false,
    paymentPlan: false,
    contingency: false,
    available: true,
    bio: "Asesor de empresas en materias comerciales, contratos y constitución de sociedades.",
    tags: ["Derecho Comercial", "Empresas", "Contratos"],
    reviewsList: [
      { author: "E.S.", text: "Nos ayudo a constituir nuestra empresa de forma rapida y segura.", rating: 5, date: "Febrero 2025" },
      { author: "G.P.", text: "Buen asesor para contratos comerciales. Entiende bien los negocios.", rating: 4, date: "Enero 2025" },
      { author: "N.B.", text: "Servicio correcto, aunque un poco caro para PYMES.", rating: 4, date: "Diciembre 2024" },
    ],
  },
  {
    id: 6,
    name: "Dra. Sofía Herrera",
    specialty: "Extranjería y Migración",
    city: "Santiago",
    rate: 70,
    rating: 4.8,
    reviews: 54,
    experience: 5,
    successRate: 96,
    verified: true,
    freeConsult: true,
    paymentPlan: true,
    contingency: false,
    available: true,
    bio: "Especialista en trámites migratorios, visas y regularización. Atención en español, inglés y portugués.",
    tags: ["Extranjería", "Migración", "Visas"],
    reviewsList: [
      { author: "V.M.", text: "Me ayudo a obtener mi visa definitiva. Muy eficiente y amable.", rating: 5, date: "Marzo 2025" },
      { author: "K.L.", text: "Excelente atencion en ingles. Regularizo mi situacion rapidamente.", rating: 5, date: "Febrero 2025" },
      { author: "B.S.", text: "Muy buena abogada, conoce todos los tramites de extranjeria.", rating: 5, date: "Enero 2025" },
    ],
  },
  {
    id: 7,
    name: "Dr. Luis Morales",
    specialty: "Derecho Tributario",
    city: "Temuco",
    rate: 180,
    rating: 4.9,
    reviews: 38,
    experience: 15,
    successRate: 90,
    verified: true,
    freeConsult: false,
    paymentPlan: false,
    contingency: false,
    available: false,
    bio: "Experto en planificación tributaria y defensa ante el SII. Ex funcionario del Servicio de Impuestos Internos.",
    tags: ["Derecho Tributario", "Impuestos", "SII"],
    reviewsList: [
      { author: "T.R.", text: "Resolvio mi problema con el SII de forma impecable. Muy conocedor.", rating: 5, date: "Febrero 2025" },
      { author: "O.M.", text: "Excelente planificacion tributaria para mi empresa. Lo recomiendo.", rating: 5, date: "Enero 2025" },
      { author: "I.C.", text: "Profesional de alto nivel. Vale la pena su tarifa.", rating: 5, date: "Diciembre 2024" },
    ],
  },
  {
    id: 8,
    name: "Dra. Carmen Silva",
    specialty: "Derecho de Familia",
    city: "La Serena",
    rate: 60,
    rating: 4.4,
    reviews: 22,
    experience: 4,
    successRate: 82,
    verified: true,
    freeConsult: true,
    paymentPlan: true,
    contingency: true,
    available: true,
    bio: "Joven abogada comprometida con casos de familia. Especialista en mediación y acuerdos extrajudiciales.",
    tags: ["Derecho de Familia", "Mediación", "Custodia"],
    reviewsList: [
      { author: "Y.F.", text: "Muy buena mediadora. Logro un acuerdo justo para ambas partes.", rating: 5, date: "Marzo 2025" },
      { author: "W.G.", text: "Joven pero muy capaz. Precio accesible y buen servicio.", rating: 4, date: "Febrero 2025" },
      { author: "U.H.", text: "Me ayudo con la custodia de mis hijos. Muy empatica.", rating: 4, date: "Enero 2025" },
    ],
  },
]

export const mockCases = [
  {
    id: "1",
    title: "Divorcio Consensual",
    type: "Derecho de Familia",
    status: "active" as const,
    lawyer: { name: "Dra. María González", specialization: "Derecho de Familia" },
    progress: 75,
    lastUpdate: "Hace 2 días",
    nextAction: "Revisión de documentos",
    priority: "high",
    documents: 12,
    messages: 8,
    createdAt: "2024-01-15",
    description: "Proceso de divorcio de mutuo acuerdo con distribución de bienes y custodia compartida de dos hijos menores.",
  },
  {
    id: "2",
    title: "Demanda Laboral por Despido Injustificado",
    type: "Derecho Laboral",
    status: "pending" as const,
    lawyer: { name: "Dr. Carlos Ruiz", specialization: "Derecho Laboral" },
    progress: 30,
    lastUpdate: "Hace 1 semana",
    nextAction: "Esperar respuesta del empleador",
    priority: "medium",
    documents: 6,
    messages: 3,
    createdAt: "2024-02-01",
    description: "Demanda por despido sin causa justificada después de 5 años de servicio. Se busca indemnización completa.",
  },
  {
    id: "3",
    title: "Compraventa Departamento Providencia",
    type: "Derecho Inmobiliario",
    status: "completed" as const,
    lawyer: { name: "Dra. Ana López", specialization: "Derecho Inmobiliario" },
    progress: 100,
    lastUpdate: "Hace 1 mes",
    nextAction: "Caso completado",
    priority: "low",
    documents: 15,
    messages: 12,
    createdAt: "2023-12-10",
    description: "Compraventa exitosa de departamento en Providencia. Todos los trámites legales completados.",
  },
  {
    id: "4",
    title: "Regularización Visa Definitiva",
    type: "Extranjería y Migración",
    status: "active" as const,
    lawyer: { name: "Dra. Sofía Herrera", specialization: "Migración" },
    progress: 50,
    lastUpdate: "Ayer",
    nextAction: "Presentar documentos en PDI",
    priority: "high",
    documents: 8,
    messages: 5,
    createdAt: "2024-03-01",
    description: "Proceso de obtención de visa definitiva para profesional extranjero con contrato de trabajo.",
  },
  {
    id: "5",
    title: "Revision de contrato de arriendo",
    type: "Derecho Civil",
    status: "waiting" as const,
    lawyer: { name: "Dr. Pedro Vasquez", specialization: "Derecho Comercial" },
    progress: 5,
    lastUpdate: "hace 1 hora",
    nextAction: "Esperando confirmacion del abogado",
    priority: "medium",
    documents: 1,
    messages: 0,
    createdAt: "2025-01-25",
    description: "Revision de contrato de arriendo comercial antes de firmar con el arrendador.",
  },
  {
    id: "6",
    title: "Consulta tributaria PYME",
    type: "Derecho Tributario",
    status: "rejected" as const,
    lawyer: { name: "Dr. Luis Morales", specialization: "Derecho Tributario" },
    progress: 0,
    lastUpdate: "hace 3 dias",
    nextAction: "Buscar otro abogado",
    priority: "low",
    documents: 0,
    messages: 1,
    createdAt: "2025-01-20",
    description: "Consulta sobre obligaciones tributarias para empresa recien constituida.",
  },
]

export const mockClientCases = [
  {
    id: "1",
    title: "Demanda por despido injustificado",
    type: "Derecho Laboral",
    urgency: "urgent",
    budgetMin: 80,
    budgetMax: 150,
    city: "Santiago",
    clientType: "Particular",
    description: "Fui despedido sin previo aviso después de 3 años en la empresa. Necesito asesoría para demandar por despido injustificado y obtener indemnización.",
    publishedAt: "Hace 2 días",
    responseNeeded: "Esta semana",
    caseType: "Representación completa",
  },
  {
    id: "2",
    title: "Divorcio con división de bienes",
    type: "Derecho de Familia",
    urgency: "normal",
    budgetMin: 100,
    budgetMax: 200,
    city: "Santiago",
    clientType: "Particular",
    description: "Necesito un abogado para tramitar mi divorcio. Hay bienes que dividir y un hijo menor de edad.",
    publishedAt: "Hace 3 días",
    responseNeeded: "Próximas 2 semanas",
    caseType: "Representación completa",
  },
  {
    id: "3",
    title: "Revisión contrato de arriendo comercial",
    type: "Derecho Comercial",
    urgency: "very-urgent",
    budgetMin: 50,
    budgetMax: 100,
    city: "Valparaíso",
    clientType: "Empresa",
    description: "Necesito revisión urgente de contrato de arriendo para local comercial antes de firmar.",
    publishedAt: "Hace 1 día",
    responseNeeded: "Mañana",
    caseType: "Asesoría puntual",
  },
  {
    id: "4",
    title: "Compraventa propiedad rural",
    type: "Derecho Inmobiliario",
    urgency: "normal",
    budgetMin: 120,
    budgetMax: 180,
    city: "Temuco",
    clientType: "Particular",
    description: "Compra de terreno agrícola, necesito verificación de títulos y redacción de contrato.",
    publishedAt: "Hace 5 días",
    responseNeeded: "Próximo mes",
    caseType: "Representación completa",
  },
  {
    id: "5",
    title: "Regularización migratoria",
    type: "Extranjería y Migración",
    urgency: "urgent",
    budgetMin: 60,
    budgetMax: 120,
    city: "Santiago",
    clientType: "Particular",
    description: "Visa de trabajo expirada, necesito regularizar mi situación migratoria lo antes posible.",
    publishedAt: "Hace 4 días",
    responseNeeded: "Esta semana",
    caseType: "Representación completa",
  },
  {
    id: "6",
    title: "Defensa por accidente de tránsito",
    type: "Derecho Penal",
    urgency: "very-urgent",
    budgetMin: 150,
    budgetMax: 300,
    city: "Concepción",
    clientType: "Particular",
    description: "Acusado de causar lesiones en accidente de tránsito. Necesito defensa penal urgente.",
    publishedAt: "Hace 6 horas",
    responseNeeded: "Hoy",
    caseType: "Representación completa",
  },
]

export const mockConversations = [
  {
    id: "1",
    lawyerName: "Dra. María González",
    lawyerSpecialty: "Derecho de Familia",
    lastMessage: "Perfecto, nos vemos mañana a las 10:00 para revisar los documentos.",
    timestamp: "10:30",
    unread: 2,
    online: true,
    messages: [
      { id: "1", sender: "lawyer", text: "Buenos días, ¿cómo está?", time: "09:00" },
      { id: "2", sender: "client", text: "Buenos días Dra. González, bien gracias. Quería consultar sobre mi caso.", time: "09:05" },
      { id: "3", sender: "lawyer", text: "Por supuesto, dígame en qué puedo ayudarle.", time: "09:10" },
      { id: "4", sender: "client", text: "Necesito saber qué documentos debo preparar para la audiencia de la próxima semana.", time: "09:15" },
      { id: "5", sender: "lawyer", text: "Para la audiencia necesitará: certificado de matrimonio, carnet de identidad de ambas partes, y los acuerdos previos que hayamos firmado.", time: "09:20" },
      { id: "6", sender: "client", text: "Entendido. ¿Podemos reunirnos mañana para revisar todo?", time: "10:00" },
      { id: "7", sender: "lawyer", text: "Perfecto, nos vemos mañana a las 10:00 para revisar los documentos.", time: "10:30" },
    ],
  },
  {
    id: "2",
    lawyerName: "Dr. Carlos Ruiz",
    lawyerSpecialty: "Derecho Laboral",
    lastMessage: "Ya recibí la respuesta del empleador. Tenemos buenas noticias.",
    timestamp: "Ayer",
    unread: 0,
    online: false,
    messages: [
      { id: "1", sender: "lawyer", text: "Hola, le escribo para informarle sobre el avance de su caso.", time: "14:00" },
      { id: "2", sender: "client", text: "Hola Dr. Ruiz, ¿hay novedades?", time: "14:30" },
      { id: "3", sender: "lawyer", text: "Sí, el empleador recibió la demanda y tiene 15 días para responder.", time: "14:35" },
      { id: "4", sender: "client", text: "¿Qué cree que pasará?", time: "14:40" },
      { id: "5", sender: "lawyer", text: "Por experiencia, es probable que busquen negociar antes del juicio.", time: "14:45" },
      { id: "6", sender: "lawyer", text: "Ya recibí la respuesta del empleador. Tenemos buenas noticias.", time: "16:00" },
    ],
  },
]

export const mockActivity = [
  { id: "1", type: "case-update", message: "Dra. González actualizó el estado de tu caso", time: "Hace 2 horas", icon: "folder" },
  { id: "2", type: "message", message: "Nuevo mensaje de Dr. Ruiz", time: "Hace 5 horas", icon: "message" },
  { id: "3", type: "document", message: "Se subió un nuevo documento a tu caso", time: "Ayer", icon: "file" },
  { id: "4", type: "appointment", message: "Recordatorio: Cita mañana a las 10:00", time: "Ayer", icon: "calendar" },
  { id: "5", type: "case-update", message: "Tu caso cambió a estado 'En Progreso'", time: "Hace 2 días", icon: "folder" },
]

export const mockDocuments = [
  { id: "1", name: "Certificado de Matrimonio.pdf", type: "PDF", date: "15/01/2024", uploadedBy: "Cliente", size: "245 KB" },
  { id: "2", name: "Carnet de Identidad - Copia.pdf", type: "PDF", date: "15/01/2024", uploadedBy: "Cliente", size: "1.2 MB" },
  { id: "3", name: "Acuerdo de División de Bienes.docx", type: "DOCX", date: "20/01/2024", uploadedBy: "Abogado", size: "89 KB" },
  { id: "4", name: "Poder Simple Firmado.pdf", type: "PDF", date: "22/01/2024", uploadedBy: "Cliente", size: "156 KB" },
]

export const mockNextSteps = [
  { id: "1", text: "Reunir documentos de identidad", completed: true, dueDate: "15/01/2024", assignedTo: "client" },
  { id: "2", text: "Firmar poder simple", completed: true, dueDate: "20/01/2024", assignedTo: "client" },
  { id: "3", text: "Revisar propuesta de acuerdo", completed: false, dueDate: "25/01/2024", assignedTo: "lawyer" },
  { id: "4", text: "Asistir a audiencia de mediación", completed: false, dueDate: "30/01/2024", assignedTo: "client" },
]
